# version: '3.8'

# services:
#   vector-db:
#     image: qdrant/qdrant
#     ports:
#       - 6333:6333
#     volumes:
#       - qdrant_data:/qdrant/storage

#   streamlit-app:
#     build: .
#     ports:
#       - 8501:8501
#     environment:
#       - OPENAI_API_KEY=${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}
#     volumes:
#       - .:/app
#     depends_on:
#       - vector-db

# volumes:
#   qdrant_data:

services:
  streamlit-app:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run app.py
    ports:
      - "8501:8501"
